import type { HelpGuide } from '../types';

export const catalogue: HelpGuide[] = [
  {
    id: 'prestation-creer',
    category: 'catalogue',
    title: 'Créer une prestation et son prix',
    summary: 'Ajoutez vos plats, vos boissons, votre matériel et votre personnel au catalogue : ils se glissent ensuite dans chaque devis, avec leur prix.',
    keywords: ['prestation', 'plat', 'menu', 'tarif', 'prix', 'catalogue', 'carte', 'produit', 'service', 'description', 'prix de revient', 'prix enfant'],
    href: '/prestations',
    steps: [
      { title: 'Ouvrez « Prestations », puis cliquez sur « Nouvelle prestation »', text: 'La prestation se remplit sur une page à part.' },
      { title: 'Donnez un nom et un « Prix unitaire HT »', text: 'Ce sont les deux champs obligatoires. « Prix enfant HT » et « Prix de revient » sont facultatifs ; avec un prix de revient, la marge s’affiche.' },
      { title: 'Choisissez la catégorie et la sous-catégorie', text: 'Elles rangent la prestation dans le catalogue. « Nouvelle catégorie », sous le champ, en crée une sans quitter la page.' },
      { title: 'Rédigez la description', text: 'L’« Aperçu dans un devis » montre la ligne du tableau et la prestation dans la carte du menu, telles que le client les lira. Sur téléphone, il est dans l’onglet « Aperçu ».' },
      { title: 'Cliquez sur « Ajouter la prestation »', text: 'Ou appuyez sur Entrée dans un champ. La liste revient, avec la prestation mise en évidence.' },
    ],
    notes: [
      'Pour corriger une prestation, cliquez sur son nom dans le catalogue : sa page s’ouvre, « Enregistrer » ramène à la liste au même endroit. Les deux icônes à droite de la ligne la dupliquent ou la suppriment.',
      'Pour une longue carte (polices, couleurs, version anglaise), « Ouvrir l’éditeur de fiche » ouvre l’éditeur plein écran. Quand une fiche existe, c’est elle qui figure dans la carte du menu, à la place de la description.',
      'Si vous quittez la page sans enregistrer, l’app demande confirmation.',
      'Le prix se change aussi directement dans la liste, sans ouvrir la prestation.',
      '« Importer un CSV » ajoute plusieurs prestations d’un coup. Celles qui existent déjà sont ignorées, et le prix des nouvelles reste à compléter.',
    ],
  },
  {
    id: 'prestation-prix',
    category: 'catalogue',
    title: 'Changer un prix directement dans la liste',
    summary: 'Corrigez le prix d’une prestation sans ouvrir sa fiche : vous tapez, c’est enregistré.',
    keywords: ['prix', 'tarif', 'modifier le prix', 'changer le prix', 'corriger', 'hors taxes', 'ht', 'liste', 'rapide', 'catalogue'],
    href: '/prestations',
    steps: [
      { title: 'Ouvrez « Prestations »', text: 'Le prix hors taxes de chaque prestation est à droite de sa ligne.' },
      { title: 'Cliquez sur le prix', text: 'Il devient un champ, déjà sélectionné.' },
      { title: 'Tapez le nouveau prix', text: 'Avec une virgule ou un point pour les centimes.' },
      { title: 'Validez avec la touche Entrée', text: 'Ou cliquez ailleurs. Une coche verte confirme l’enregistrement.' },
    ],
    notes: [
      'La touche Échap annule la saisie et remet l’ancien prix.',
      'Les devis déjà faits gardent l’ancien prix. Le nouveau sert aux prochains devis.',
    ],
  },
  {
    id: 'reviser-prix',
    category: 'catalogue',
    title: 'Augmenter ou baisser tous vos prix d’un pourcentage',
    summary: 'Appliquez une hausse de tarifs, par exemple 4 %, à tout le catalogue ou à une seule catégorie, avec un aperçu avant de valider.',
    keywords: ['réviser', 'révision', 'augmenter', 'hausse', 'baisse', 'pourcentage', '%', 'inflation', 'nouveaux tarifs', 'arrondi', 'prix', 'tous les prix'],
    href: '/prestations',
    steps: [
      { title: 'Choisissez ce qui doit changer', text: 'Pour une seule catégorie, cliquez d’abord sur son onglet. Sinon, restez sur « Tout ».' },
      { title: 'Cliquez sur « Réviser les prix »', text: 'Le bouton est en haut de la page Prestations.' },
      { title: 'Indiquez la « Variation en % »', text: '4 pour une hausse de 4 %, -5 pour une baisse de 5 %.' },
      { title: 'Choisissez l’« Arrondi »', text: '« Au centime », « Aux 10 centimes » ou « Aux 50 centimes ».' },
      { title: 'Vérifiez l’aperçu, puis cliquez sur « Appliquer à… »', text: 'L’aperçu montre l’ancien et le nouveau prix de quelques prestations. Le bouton rappelle combien de prestations vont changer.' },
    ],
    notes: [
      'Seules les prestations qui ont un prix sont concernées.',
      'Les devis déjà faits ne changent pas.',
    ],
  },
  {
    id: 'prestations-selection',
    category: 'catalogue',
    title: 'Ranger ou supprimer plusieurs prestations d’un coup',
    summary: 'Cochez des prestations, puis changez leur catégorie ou supprimez-les en une seule fois.',
    keywords: ['cocher', 'sélection', 'sélectionner', 'plusieurs', 'en masse', 'en série', 'groupé', 'catégorie', 'déplacer', 'supprimer', 'ranger', 'tri'],
    href: '/prestations',
    steps: [
      { title: 'Cochez les prestations', text: 'La case est au début de chaque ligne. « Tout cocher », au-dessus de la liste, coche toutes les prestations affichées.' },
      { title: 'Cliquez sur « Changer de catégorie »', text: 'Choisissez la catégorie, puis la sous-catégorie si besoin.' },
      { title: 'Validez avec « Appliquer à… »', text: 'Les prestations cochées rejoignent la catégorie choisie.' },
      { title: 'Pour supprimer, cliquez sur « Supprimer »', text: 'Une fenêtre demande de confirmer. La suppression est définitive.' },
    ],
    notes: [
      '« Annuler » décoche tout.',
      'Changer d’onglet de catégorie décoche aussi les prestations.',
      'Les devis déjà faits ne changent pas.',
    ],
  },
  {
    id: 'prestation-ingredients',
    category: 'catalogue',
    title: 'Relier des ingrédients à une prestation',
    summary: 'Indiquez la quantité de chaque ingrédient par convive : c’est ce qui permet de calculer les listes de courses.',
    keywords: ['ingrédients', 'recette', 'fiche technique', 'grammage', 'quantité par personne', 'par convive', 'composition', 'courses', 'lier'],
    href: '/prestations',
    steps: [
      { title: 'Cliquez sur une prestation du catalogue', text: 'Sa page s’ouvre. Le bloc « Ingrédients par personne » se trouve en bas.' },
      { title: 'Cliquez sur « Lier un ingrédient » dans ce bloc' },
      { title: 'Cherchez l’ingrédient', text: 'Tapez au moins deux lettres dans « Rechercher un ingrédient » et cliquez sur le bon.' },
      { title: 'Indiquez la quantité par personne', text: 'Elle s’exprime dans l’unité de l’ingrédient : 0,03 pour 30 g d’un ingrédient compté en kg.' },
      { title: 'Cliquez sur « Lier »', text: 'L’ingrédient rejoint la liste avec sa quantité par personne. Le lien est enregistré aussitôt.' },
    ],
    notes: [
      'Le bloc n’apparaît que sur une prestation déjà créée : créez d’abord la prestation, puis rouvrez-la depuis le catalogue.',
      'Seuls vos propres ingrédients sont proposés. Créez ceux qui manquent dans la page « Ingrédients ».',
      'Dans la liste de courses d’un événement, chaque quantité est multipliée par le nombre de couverts.',
    ],
  },
  {
    id: 'categories',
    category: 'catalogue',
    title: 'Organiser vos catégories de prestations',
    summary: 'Les catégories et les sous-catégories rangent votre catalogue de prestations.',
    keywords: ['catégories', 'sous-catégories', 'familles', 'classement', 'rangement', 'catalogue', 'organiser', 'rubriques'],
    href: '/parametres/categories',
    steps: [
      { title: 'Ouvrez « Catégories » dans le menu « Paramètres »', text: 'La page « Mes catégories » liste chaque catégorie et ses sous-catégories.' },
      { title: 'Repérez les catégories marquées « Par défaut »', text: 'Elles sont fournies avec l’app et ne se modifient pas.' },
      { title: 'Cliquez sur « Nouvelle catégorie »', text: 'Saisissez son nom, puis validez avec la coche ou la touche Entrée.' },
      { title: 'Complétez vos propres catégories', text: 'Dans une catégorie que vous avez créée, « Ajouter une sous-catégorie » ajoute un niveau. Le crayon renomme, la corbeille supprime.' },
    ],
    notes: [
      'Supprimer une catégorie supprime aussi ses sous-catégories.',
      'Sur la page d’une prestation, « Nouvelle catégorie » crée aussi une catégorie sans quitter la saisie.',
    ],
  },
  {
    id: 'extras',
    category: 'catalogue',
    title: 'Gérer votre carnet d’extras',
    summary: 'Enregistrez vos serveurs, vos cuisiniers et vos barmans, et retrouvez leurs missions.',
    keywords: ['extras', 'personnel', 'serveurs', 'cuisiniers', 'barman', 'équipe', 'vacataires', 'staff', 'agenda', 'mission', 'carnet', 'assigner'],
    href: '/extras',
    steps: [
      { title: 'Ouvrez « Extras » dans le menu « Catalogue »' },
      { title: 'Cliquez sur « Ajouter un extra »', text: 'Le nom est obligatoire. Le téléphone, l’email et le rôle (Cuisinier, Sous-chef, Serveur, Barman, Aide, Autre) sont facultatifs.' },
      { title: 'Affectez la personne avec « Assigner »', text: 'Choisissez l’événement, le statut de départ et l’heure d’arrivée. La mission s’affiche sous son nom.' },
      { title: 'Cliquez sur une mission pour la compléter', text: 'Une fenêtre s’ouvre : statut, heure d’arrivée, notes de mission, et « Retirer » pour annuler l’affectation.' },
      { title: 'Passez en vue « Agenda »', text: 'Un tableau de huit semaines montre qui travaille quand, avec la couleur du statut.' },
    ],
    notes: [
      'L’icône de lien copie l’adresse de la page personnelle de l’extra, à lui transmettre par SMS ou par email.',
      'Un clic sur le nom d’un extra rouvre sa fiche pour la modifier.',
      'La même affectation se fait depuis la fiche d’un événement, onglet « Extras ».',
    ],
  },
  {
    id: 'modeles-presentation',
    category: 'catalogue',
    title: 'Choisir le style de vos devis',
    summary: 'Le style et la police proposés à chaque nouveau devis, vus sur un devis d’exemple.',
    keywords: ['style', 'présentation', 'couleur', 'police', 'modèle', 'mise en page', 'charte', 'apparence'],
    href: '/modeles',
    steps: [
      { title: 'Ouvrez « Styles de devis »', text: 'Dans le menu, rubrique Paramètres.' },
      { title: 'Comparez les styles', text: 'Chaque vignette montre un devis d’exemple avec le nom de votre entreprise. Cliquez dessus pour la voir en grand.' },
      { title: 'Choisissez un style et une police', text: 'Cliquez sur « Choisir » sous le style voulu, puis sélectionnez la police.' },
      { title: 'Cliquez sur « Enregistrer mes choix »', text: 'Vos prochains devis partiront avec ce style et cette police.' },
    ],
    notes: ['Un devis déjà créé garde son style. Pour le changer, ouvrez-le dans l’éditeur, panneau Style.', '« Nouveau devis » sous un style crée un devis dans ce style, sans changer votre choix par défaut.'],
  },
  {
    id: 'modeles-location',
    category: 'catalogue',
    title: 'Préparer vos modèles de location',
    summary: 'Un modèle par type de réception fixe la vaisselle et le mobilier nécessaires par couvert : la location d’un événement se calcule ensuite d’un clic.',
    keywords: ['location', 'modèles de location', 'modèle', 'vaisselle', 'verres', 'assiettes', 'couverts', 'nappes', 'mobilier', 'par couvert', 'dîner assis', 'cocktail', 'loueur', 'liste de base'],
    href: '/location-templates',
    steps: [
      { title: 'Ouvrez « Modèles de location » dans le menu « Paramètres »', text: 'Chaque modèle a son bouton en haut de la page, avec son nombre d’articles.' },
      { title: 'Créez un modèle avec « Nouveau modèle »', text: 'Donnez-lui le nom d’un type de réception (dîner assis, cocktail, séminaire), puis cliquez sur « Créer le modèle ».' },
      { title: 'Cochez les articles dans la liste qui s’ouvre', text: 'Assiettes, couverts, verrerie, nappage, mobilier : la quantité habituelle par couvert est déjà remplie. Corrigez-la si besoin, puis cliquez sur « Ajouter ». Le bouton « Depuis la liste » rouvre cette liste à tout moment.' },
      { title: 'Ajoutez un article à la main avec « Ajouter un article »', text: 'Commencez à taper son nom : les articles connus sont proposés, et en choisir un remplit l’unité et la quantité. Complétez le prix unitaire HT et le fournisseur habituel, puis « Enregistrer ».' },
      { title: 'Contrôlez le coût du modèle', text: 'Sous son nom, le modèle affiche son nombre d’articles et un montant estimé pour 100 couverts.' },
      { title: 'Appliquez le modèle dans un événement', text: 'Dans l’onglet « Matériel », « Appliquer un modèle » multiplie chaque quantité par le nombre de couverts et arrondit à l’unité supérieure.' },
    ],
    notes: [
      'Pour un article partagé, comme une table de dix, indiquez 0,1 par couvert.',
      'L’unité se choisit dans une liste (pièce, jeu, lot, mètre…) : tous vos articles se comptent de la même façon.',
      'Les articles pris dans la liste arrivent sans prix : ajoutez-le avec le crayon de leur ligne.',
      'Les trois icônes à côté du nom renomment, dupliquent ou suppriment le modèle. Le dupliquer évite de tout ressaisir pour une réception proche.',
      'Modifier ou supprimer un modèle ne change pas les locations déjà générées dans vos événements.',
    ],
  },
  {
    id: 'materiel',
    category: 'catalogue',
    title: 'Tenir la liste de votre matériel',
    summary: 'Notez une fois ce que vous emportez sur vos événements : dans chaque événement, il suffit ensuite de cocher.',
    keywords: ['matériel', 'équipement', 'liste de matériel', 'chafing dish', 'étuve', 'caisse isotherme', 'bacs gastro', 'rallonge', 'à emporter', 'liste de base', 'inventaire'],
    href: '/materiel',
    steps: [
      { title: 'Ouvrez « Matériel » dans le menu « Catalogue »' },
      { title: 'Cliquez sur « Depuis la liste »', text: 'La liste de base propose le matériel courant, rangé par famille : service chaud, froid et transport, service, installation et nettoyage. Quand votre liste est vide, le bouton s’appelle « Partir de la liste de base ».' },
      { title: 'Cochez ce que vous possédez', text: 'Ajustez la quantité que vous emportez d’habitude, puis cliquez sur « Ajouter ».' },
      { title: 'Ajoutez un article à vous avec « Nouvel article »', text: 'Saisissez son nom, sa quantité et son unité. Cochez « Cette quantité est par couvert » si elle dépend du nombre d’invités, puis cliquez sur « Enregistrer ».' },
      { title: 'Corrigez ou retirez un article', text: 'Un clic sur la ligne la rouvre. La corbeille retire l’article de votre liste.' },
    ],
    notes: [
      'Dans un événement, onglet « Matériel », « Choisir dans ma liste » reprend cette liste.',
      'En tapant un nom connu, l’unité et la quantité habituelle se remplissent seules.',
      'Retirer un article de votre liste ne le retire pas des événements où il figure déjà.',
    ],
  },
];
