import type { HelpGuide } from '../types';

export const devis: HelpGuide[] = [
  {
    id: 'page-devis',
    category: 'devis',
    title: 'S’y retrouver dans la page Devis',
    summary: 'Tous vos devis au même endroit, rangés en volets, avec un filtre, un tri et une recherche.',
    keywords: ['liste', 'volet', 'onglet', 'en cours', 'confirmés', 'refusés', 'prospects', 'filtre', 'tri', 'trier', 'recherche', 'chercher', 'retrouver', 'montant'],
    href: '/devis',
    steps: [
      { title: 'Choisissez un volet', text: '« En cours », « Confirmés », « Refusés » ou « Prospects ». Le chiffre à côté de chaque nom compte ses devis.' },
      { title: 'Filtrez par statut', text: 'La liste « Tous les statuts » ne garde qu’une étape du volet, par exemple « Devis envoyé ».' },
      { title: 'Changez le tri', text: '« Plus récents », « Date d’événement », « Montant » ou « Nom A-Z ».' },
      { title: 'Cherchez un devis', text: 'Tapez un nom de client ou un type d’événement dans « Filtrer par client ou événement ».' },
      { title: 'Ouvrez un devis', text: 'Un clic sur la ligne ouvre sa fiche. Le bouton « ⋯ » au bout de la ligne ouvre ses actions.' },
    ],
    notes: [
      'Le volet « Prospects » liste les demandes reçues qui ne sont pas encore devenues des devis.',
      'La recherche porte sur tous les dossiers, pas seulement sur celui qui est ouvert.',
      'La case au début de chaque ligne sert à traiter plusieurs devis d’un coup : statut, dossier, suppression.',
    ],
  },
  {
    id: 'devis-selection',
    category: 'devis',
    title: 'Traiter plusieurs devis d’un coup',
    summary: 'Cochez des devis, puis changez leur statut, rangez-les dans un dossier ou supprimez-les en une seule fois.',
    keywords: ['cocher', 'sélection', 'sélectionner', 'plusieurs', 'en masse', 'groupé', 'statut', 'déplacer', 'dossier', 'supprimer', 'ménage', 'archiver'],
    href: '/devis',
    steps: [
      { title: 'Cochez les devis', text: 'La case est au début de chaque ligne. « Tout cocher », au-dessus de la liste, coche tous les devis affichés.' },
      { title: 'Changez leur statut', text: 'Dans la liste « Changer le statut… », choisissez l’étape : tous les devis cochés passent à ce statut.' },
      { title: 'Ou rangez-les avec « Déplacer »', text: 'Cliquez sur le dossier d’arrivée.' },
      { title: 'Ou supprimez-les avec « Supprimer »', text: 'La fenêtre signale les devis qui ne sont pas des brouillons. Confirmez avec « Supprimer… devis ».' },
    ],
    notes: [
      '« Annuler » décoche tout. Changer de volet ou de dossier décoche aussi.',
      'Quand un devis vient d’une demande reçue, la demande suit son nouveau statut.',
      'La suppression est définitive.',
    ],
  },
  {
    id: 'modifier-devis',
    category: 'devis',
    title: 'Modifier le texte d’un devis',
    summary: 'Corrigez le texte du devis directement dans la page, tel que le client le verra.',
    keywords: ['éditeur', 'modifier', 'corriger', 'texte', 'rédiger', 'mise en forme', 'gras', 'couleur', 'police', 'enregistrer', 'document'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le devis dans l’éditeur', text: 'Dans la page Devis, ouvrez le menu « ⋯ » du devis, puis choisissez « Modifier le devis ».' },
      { title: 'Cliquez dans le texte et écrivez', text: 'Phrase d’accueil, intitulés, descriptions : tout se corrige dans la page.' },
      { title: 'Mettez en forme', text: 'Sélectionnez un passage, puis utilisez la barre du haut : gras, italique, titres, couleurs, police et taille.' },
      { title: 'Cliquez sur « Enregistrer »', text: 'Le bouton est dans le menu de gauche. Ctrl+S fait la même chose. « Retour aux devis » ramène à la liste.' },
    ],
    notes: [
      'Enregistrez avant de quitter l’éditeur.',
      'Si votre session expire pendant que vous écrivez, un message l’annonce : votre texte est gardé sur l’appareil. Cliquez sur « Se reconnecter », connectez-vous dans le nouvel onglet, puis revenez et enregistrez.',
      'Si vous avez réécrit l’introduction ou le titre du menu à la main, un changement de client ou d’événement ne les remplace pas. Un message vous invite à les relire.',
    ],
  },
  {
    id: 'saut-de-page',
    category: 'devis',
    title: 'Commencer une partie sur une nouvelle page',
    summary: 'Le saut de page force la suite du devis à commencer en haut de la page suivante, à l’impression et dans le PDF.',
    keywords: ['saut de page', 'nouvelle page', 'page suivante', 'mise en page', 'impression', 'pdf', 'couper', 'séparer', 'page blanche'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le devis dans l’éditeur', text: 'Menu « ⋯ » du devis, puis « Modifier le devis ».' },
      { title: 'Cliquez à l’endroit où la page doit se terminer', text: 'Par exemple juste avant le titre du menu.' },
      { title: 'Cliquez sur le bouton « Saut de page »', text: 'Il est dans la barre d’outils, après les boutons d’alignement. Un trait pointillé marqué « Saut de page » apparaît.' },
      { title: 'Enregistrez', text: 'À l’impression et dans le PDF, la suite commence sur une nouvelle page.' },
    ],
    notes: [
      'Le trait pointillé n’apparaît ni sur le devis du client, ni dans le PDF : seule la coupure de page reste.',
    ],
  },
  {
    id: 'editeur-actions',
    category: 'devis',
    title: 'Changer le statut, envoyer ou dupliquer depuis l’éditeur',
    summary: 'Pendant que vous écrivez le devis, le menu de gauche donne son statut, l’envoi au client, la copie et la préparation de l’événement.',
    keywords: ['éditeur', 'weboword', 'statut', 'envoyer', 'dupliquer', 'copie', 'événement', 'préparer', 'menu', 'barre latérale', 'sans quitter'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le devis dans l’éditeur', text: 'Les actions sont en bas du menu de gauche, sous « Enregistrer » et « Imprimer ou PDF ».' },
      { title: 'Changez le « Statut du devis »', text: 'Choisissez l’étape dans la liste. Le changement est pris en compte aussitôt.' },
      { title: 'Cliquez sur « Envoyer au client »', text: 'Le devis est d’abord enregistré, puis la fenêtre d’envoi s’ouvre, avec l’email du client et un message à relire.' },
      { title: 'Cliquez sur « Dupliquer » pour repartir de ce devis', text: 'Le devis est enregistré, puis la fenêtre de copie s’ouvre : client, date, couverts.' },
      { title: 'Passez à la préparation avec « Préparer l’événement »', text: 'Le bouton apparaît quand le devis est « Validé », « Acompte reçu » ou « Payé ».' },
    ],
    notes: [
      'Sur téléphone, ces actions sont dans le bouton « Menu » en bas de l’écran.',
    ],
  },
  {
    id: 'editeur-telephone',
    category: 'devis',
    title: 'Modifier un devis sur téléphone',
    summary: 'L’éditeur s’adapte à l’écran du téléphone : la page tient dans la largeur, les outils se déplient à la demande.',
    keywords: ['téléphone', 'mobile', 'smartphone', 'iphone', 'android', 'éditeur', 'zoom', 'taille réelle', 'page entière', 'outils', 'menu', 'en déplacement'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le devis', text: 'Page Devis, menu « ⋯ » du devis, puis « Modifier le devis ». La page entière tient dans l’écran.' },
      { title: 'Touchez « Taille réelle » pour écrire', text: 'Le texte s’affiche à sa vraie taille. « Page entière » revient à la vue d’ensemble.' },
      { title: 'Touchez « Plus d’outils »', text: 'La barre de mise en forme se déplie en entier : gras, titres, couleurs, saut de page. « Moins » la replie.' },
      { title: 'Touchez « Menu », en bas de l’écran', text: 'Il ouvre les panneaux du devis (client, prestations, événement, style) et les actions : statut, « Envoyer au client », « Dupliquer », « Préparer l’événement ».' },
      { title: 'Touchez « Enregistrer »', text: 'Le bouton est en bas à droite. L’icône de téléchargement, à côté de « Menu », enregistre le devis en PDF.' },
    ],
    notes: [
      'La flèche en bas à gauche ramène à la liste des devis. Enregistrez avant.',
    ],
  },
  {
    id: 'envoyer-devis',
    category: 'devis',
    title: 'Envoyer un devis au client par email',
    summary: 'Le client reçoit un email avec un lien pour consulter le devis en ligne et l’enregistrer en PDF.',
    keywords: ['envoyer', 'envoi', 'email', 'mail', 'courriel', 'lien', 'client', 'message', 'proposition', 'pdf', 'relance'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis', text: 'C’est le bouton « ⋯ » au bout de sa ligne.' },
      { title: 'Choisissez « Envoyer au client »', text: 'La fenêtre « Envoyer le devis au client » s’ouvre.' },
      { title: 'Vérifiez l’adresse et le message', text: 'L’email du client est déjà rempli quand il est connu. Le message proposé reprend l’événement et sa date ; il se modifie librement.' },
      { title: 'Cliquez sur « Envoyer »', text: 'Une confirmation rappelle à quelle adresse l’email est parti.' },
    ],
    notes: [
      'Le client reçoit un lien vers le devis, pas de pièce jointe.',
      'À l’envoi, un devis encore à faire passe en « Devis envoyé ».',
      'Les réponses du client arrivent dans votre boîte email.',
      'Dans l’éditeur, « Envoyer au client » est aussi dans le menu de gauche : le devis est enregistré avant l’envoi.',
    ],
  },
  {
    id: 'imprimer-devis',
    category: 'devis',
    title: 'Imprimer un devis ou l’enregistrer en PDF',
    summary: 'Sortez le devis sur papier ou en fichier PDF depuis la fenêtre d’impression.',
    keywords: ['imprimer', 'impression', 'pdf', 'papier', 'fichier', 'télécharger', 'exporter', 'enregistrer'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis', text: 'C’est le bouton « ⋯ » au bout de sa ligne.' },
      { title: 'Choisissez « Imprimer ou enregistrer en PDF »', text: 'Le devis s’ouvre dans un nouvel onglet, avec la fenêtre d’impression de votre navigateur.' },
      { title: 'Imprimez, ou enregistrez le fichier', text: 'Pour un PDF, choisissez l’enregistrement en PDF comme destination dans la fenêtre d’impression.' },
    ],
    notes: [
      'Le bouton « PDF » de la fiche du devis ouvre la même page.',
    ],
  },
  {
    id: 'statut-devis',
    category: 'devis',
    title: 'Changer le statut d’un devis',
    summary: 'Le statut dit où en est chaque devis, de la première demande au paiement.',
    keywords: ['statut', 'état', 'étape', 'avancement', 'validé', 'confirmé', 'acompte', 'payé', 'refus', 'refusé', 'brochure', 'dégustation', 'rendez-vous', 'événement'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur le devis dans la liste', text: 'Sa fiche s’ouvre à droite.' },
      { title: 'Choisissez le nouveau statut', text: 'Sous « Statut », cliquez sur l’étape atteinte. Le changement est pris en compte aussitôt.' },
      { title: 'Retrouvez le devis dans son volet', text: '« Validé », « Acompte reçu » et « Payé » le rangent dans « Confirmés ». « Refus client » et « Refus traiteur » le rangent dans « Refusés ».' },
      { title: 'Préparez l’événement', text: 'Un devis confirmé devient un événement : le bouton « Gérer l’événement », en bas de la fiche, ouvre sa préparation.' },
    ],
    notes: [
      'Avant la décision du client, un devis passe par « Nouveau », « Brochure envoyée », « Devis à faire », « Devis envoyé », « RDV/Dég à venir », « RDV/Dég fait » (rendez-vous ou dégustation) et « Devis final ».',
      'Quand un devis vient d’une demande reçue, son statut et celui de la demande changent ensemble.',
    ],
  },
  {
    id: 'pipeline-devis',
    category: 'devis',
    title: 'Suivre vos devis en colonnes',
    summary: 'La vue « Pipeline » range les devis par statut et laisse glisser un devis d’une colonne à l’autre.',
    keywords: ['pipeline', 'colonnes', 'tableau', 'kanban', 'glisser', 'déplacer', 'statut', 'suivi', 'prospection', 'avancement'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Pipeline »', text: 'Le bouton est en haut de la page Devis, à côté de « Liste ».' },
      { title: 'Parcourez les colonnes', text: 'Une colonne par statut, avec le nombre de devis et leur montant. Les étapes suivantes sont à droite.' },
      { title: 'Glissez un devis dans une autre colonne', text: 'Son statut change aussitôt.' },
    ],
    notes: [
      'Les demandes reçues y figurent aussi, avec l’étiquette « Prospect » et le bouton « Créer le devis ».',
      'La vue « Pipeline » est proposée sur tablette et sur ordinateur.',
    ],
  },
  {
    id: 'suivi-devis',
    category: 'devis',
    title: 'Noter vos relances sur un devis',
    summary: 'Chaque devis garde ses notes de suivi : appels, relances, échanges avec le client.',
    keywords: ['relance', 'relancer', 'notes', 'suivi', 'commercial', 'appel', 'rappel', 'rappeler', 'mémo', 'nom interne', 'renommer'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur le devis dans la liste', text: 'Sa fiche s’ouvre à droite.' },
      { title: 'Ouvrez l’onglet « Suivi commercial »' },
      { title: 'Écrivez votre note', text: 'Par exemple la date d’une relance et la réponse attendue.' },
      { title: 'Cliquez sur « Sauvegarder les notes »' },
    ],
    notes: [
      'Ces notes sont pour vous : elles ne figurent pas sur le devis du client.',
      'Dans l’onglet « Aperçu », « Nom du devis (interne) » donne au devis un nom à vous, par exemple « Mariage Camille et Hugo ».',
    ],
  },
  {
    id: 'dossiers-devis',
    category: 'devis',
    title: 'Ranger vos devis dans des dossiers',
    summary: 'Regroupez vos devis par saison, par type de réception ou par client.',
    keywords: ['dossier', 'dossiers', 'ranger', 'classer', 'organiser', 'trier', 'déplacer', 'sous-dossier', 'archive'],
    href: '/devis',
    steps: [
      { title: 'Créez un dossier', text: 'Cliquez sur « Nouveau dossier », donnez-lui un nom, une couleur et une icône, puis cliquez sur « Créer ».' },
      { title: 'Rangez un devis', text: 'Ouvrez son menu « ⋯ », choisissez « Déplacer vers un dossier », puis cliquez sur le dossier.' },
      { title: 'Ouvrez un dossier', text: 'Un clic sur sa tuile n’affiche que ses devis. « Mes devis » ramène à la liste complète.' },
      { title: 'Modifiez un dossier', text: 'Le bouton « ⋯ » de sa tuile change son nom, sa couleur et son icône, ou le supprime.' },
    ],
    notes: [
      'Vous pouvez aussi glisser un devis sur la tuile d’un dossier.',
      'Supprimer un dossier ne supprime pas ses devis : ils remontent d’un niveau.',
      'Dans un dossier ouvert, « Nouveau dossier » crée un sous-dossier et « Nouveau dans ce dossier » y crée un devis.',
    ],
  },
  {
    id: 'dupliquer-devis',
    category: 'devis',
    title: 'Dupliquer un devis',
    summary: 'Repartez d’un devis existant pour un autre client, une autre date ou un autre nombre de couverts, au lieu de tout ressaisir.',
    keywords: ['dupliquer', 'copier', 'copie', 'double', 'refaire', 'réutiliser', 'modèle', 'base', 'autre client', 'autre date', 'couverts', 'même menu'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis, puis choisissez « Dupliquer »', text: 'Le menu est le bouton « ⋯ » au bout de la ligne. La fenêtre « Dupliquer le devis » s’ouvre.' },
      { title: 'Choisissez le client', text: 'Le premier bouton garde le même client. « Autre client » ouvre une recherche : tapez son nom, son email ou son entreprise, puis cliquez sur lui.' },
      { title: 'Indiquez la date et le nombre de couverts', text: 'Ceux de l’original sont proposés. Les quantités calculées sur le nombre de couverts suivent le nouveau nombre.' },
      { title: 'Gardez-le comme modèle, si vous le souhaitez', text: 'Cochez « Garder aussi ce devis comme modèle » et donnez-lui un nom. Il sera proposé dans « Partir d’un modèle ».' },
      { title: 'Cliquez sur « Créer la copie »', text: 'La copie s’ouvre dans l’éditeur, avec le même contenu et la même mise en page, mis à jour pour le client et l’événement choisis.' },
    ],
    notes: [
      'La copie démarre au statut « Devis à faire » et reste dans le dossier de l’original.',
      'Le client doit déjà être dans vos clients. Sinon, gardez le même client et changez-le ensuite dans le devis, panneau Client.',
      'Dans l’éditeur, « Dupliquer » est aussi dans le menu de gauche.',
    ],
  },
  {
    id: 'modeles-devis',
    category: 'devis',
    title: 'Partir d’un modèle de devis',
    summary: 'Un modèle garde les prestations, les textes et la mise en page d’un devis type. Le nouveau devis part de là, adapté à vos couverts.',
    keywords: ['modèle', 'modèles', 'gabarit', 'devis type', 'trame', 'base', 'réutiliser', 'bibliothèque', 'renommer', 'contenu de départ', 'couverts'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Partir d’un modèle »', text: 'Le bouton est en haut de la page Devis. Chaque modèle montre la première page de son document : cliquez sur la vignette pour le voir en grand.' },
      { title: 'Cliquez sur « Utiliser » sous le modèle qui convient', text: 'La création guidée du devis s’ouvre.' },
      { title: 'Décrivez l’événement, puis choisissez le client', text: 'Le type, la date et le nombre de couverts, puis le client, comme pour tout nouveau devis.' },
      { title: 'Vérifiez le « Contenu de départ »', text: 'À l’étape Style, le modèle choisi y est déjà sélectionné, avec son style.' },
      { title: 'Cliquez sur « Créer le devis »', text: 'Le devis s’ouvre dans l’éditeur : client et événement sont remplis, et les quantités comptées par couvert suivent votre nombre de couverts. Les forfaits ne changent pas.' },
    ],
    notes: [
      'Depuis « Nouveau devis », le même choix se fait à l’étape Style, dans « Contenu de départ ». « Document vierge » part d’une page blanche.',
      'Pour créer un modèle, dupliquez un devis et cochez « Garder aussi ce devis comme modèle ». Le bouton « Partir d’un modèle » apparaît dès le premier modèle enregistré.',
      'Le crayon renomme un modèle, la corbeille le supprime.',
    ],
  },
  {
    id: 'importer-devis',
    category: 'devis',
    title: 'Importer un devis fait ailleurs',
    summary: 'Un devis préparé dans un autre logiciel rejoint vos devis, avec son montant et son fichier.',
    keywords: ['importer', 'import', 'ancien devis', 'autre logiciel', 'word', 'pdf', 'fichier', 'document', 'joindre', 'reprendre'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Importer »', text: 'Le bouton est en haut de la page Devis.' },
      { title: 'Renseignez le client', text: '« Nouveau client » ou « Client existant ». Le prénom et le nom sont obligatoires.' },
      { title: 'Renseignez l’événement', text: 'La date est obligatoire. Ajoutez le type, le nombre de couverts et le montant total TTC.' },
      { title: 'Joignez le fichier du devis', text: 'PDF, Word, OpenDocument ou image.' },
      { title: 'Cliquez sur « Importer le devis »' },
    ],
    notes: [
      'Un devis importé arrive au statut « Validé », dans le volet « Confirmés » : il compte comme un événement à préparer.',
      'Il porte l’étiquette « Importé ». Dans son menu « ⋯ », « Modifier l’import » corrige ces informations ou remplace le fichier.',
      'Un devis importé ne s’envoie pas avec « Envoyer au client ».',
    ],
  },
  {
    id: 'marge-devis',
    category: 'devis',
    title: 'Suivre les coûts et la marge d’un devis',
    summary: 'Pour chaque devis : le chiffre d’affaires, les charges et la marge, prestation par prestation.',
    keywords: ['marge', 'coût', 'coûts', 'prix de revient', 'rentabilité', 'bénéfice', 'finance', 'charges', 'frais', 'chiffre d’affaires'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis, puis choisissez « Marge et coûts »', text: 'Le menu est le bouton « ⋯ » au bout de la ligne.' },
      { title: 'Lisez les trois chiffres du haut', text: '« Chiffre d’affaires », « Charges » et « Marge brute », en euros et en pourcentage.' },
      { title: 'Saisissez un coût de revient', text: 'Cliquez dans la colonne « Coût » d’une prestation, tapez son coût unitaire hors taxes, puis validez avec la touche Entrée.' },
      { title: 'Ajoutez les frais propres à ce devis', text: 'Sous « Frais additionnels », cliquez sur « + Ajouter » : personnel en plus, transport, location.' },
      { title: 'Consultez la synthèse', text: 'En bas de la fiche, « Marge brute estimée » tient compte des coûts et des frais.' },
    ],
    notes: [
      'Le coût saisi est enregistré sur la prestation de votre catalogue : il sert à tous vos devis.',
      'Une ligne qui ne vient pas du catalogue n’a pas de coût, et sa marge n’est pas calculée.',
    ],
  },
];
