import type { HelpGuide } from '../types';

export const devis: HelpGuide[] = [
  {
    id: 'page-devis',
    category: 'devis',
    title: 'S’y retrouver dans la page Devis',
    summary: 'Tous vos devis au même endroit, rangés en volets, avec un filtre, un tri et une recherche.',
    keywords: ['liste', 'volet', 'onglet', 'en cours', 'confirmés', 'refusés', 'prospects', 'filtre', 'tri', 'trier', 'recherche', 'chercher', 'retrouver', 'montant'],
    href: '/devis',
    steps: [
      { title: 'Choisissez un volet', text: '« En cours », « Confirmés », « Refusés » ou « Prospects ». Le chiffre à côté de chaque nom compte ses devis.' },
      { title: 'Filtrez par statut', text: 'La liste « Tous les statuts » ne garde qu’une étape du volet, par exemple « Devis envoyé ».' },
      { title: 'Changez le tri', text: '« Plus récents », « Date d’événement », « Montant » ou « Nom A-Z ».' },
      { title: 'Cherchez un devis', text: 'Tapez un nom de client ou un type d’événement dans « Filtrer par client ou événement ».' },
      { title: 'Ouvrez un devis', text: 'Un clic sur la ligne ouvre sa fiche. Le bouton « ⋯ » au bout de la ligne ouvre ses actions.' },
    ],
    notes: [
      'Le volet « Prospects » liste les demandes reçues qui ne sont pas encore devenues des devis.',
      'La recherche porte sur tous les dossiers, pas seulement sur celui qui est ouvert.',
    ],
  },
  {
    id: 'modifier-devis',
    category: 'devis',
    title: 'Modifier le texte d’un devis',
    summary: 'Corrigez le texte du devis directement dans la page, tel que le client le verra.',
    keywords: ['éditeur', 'modifier', 'corriger', 'texte', 'rédiger', 'mise en forme', 'gras', 'couleur', 'police', 'enregistrer', 'document'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le devis dans l’éditeur', text: 'Dans la page Devis, ouvrez le menu « ⋯ » du devis, puis choisissez « Modifier le devis ».' },
      { title: 'Cliquez dans le texte et écrivez', text: 'Phrase d’accueil, intitulés, descriptions : tout se corrige dans la page.' },
      { title: 'Mettez en forme', text: 'Sélectionnez un passage, puis utilisez la barre du haut : gras, italique, titres, couleurs, police et taille.' },
      { title: 'Cliquez sur « Enregistrer »', text: 'Le bouton est dans le menu de gauche. « Retour aux devis » ramène à la liste.' },
    ],
    notes: [
      'Enregistrez avant de quitter l’éditeur.',
    ],
  },
  {
    id: 'envoyer-devis',
    category: 'devis',
    title: 'Envoyer un devis au client par email',
    summary: 'Le client reçoit un email avec un lien pour consulter le devis en ligne et l’enregistrer en PDF.',
    keywords: ['envoyer', 'envoi', 'email', 'mail', 'courriel', 'lien', 'client', 'message', 'proposition', 'pdf', 'relance'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis', text: 'C’est le bouton « ⋯ » au bout de sa ligne.' },
      { title: 'Choisissez « Envoyer au client »' },
      { title: 'Vérifiez l’adresse et le message', text: 'L’email du client est déjà rempli quand il est connu. Le message proposé se modifie librement.' },
      { title: 'Cliquez sur « Envoyer »', text: 'Une confirmation rappelle à quelle adresse l’email est parti.' },
    ],
    notes: [
      'Le client reçoit un lien vers le devis, pas de pièce jointe.',
      'À l’envoi, un devis encore à faire passe en « Devis envoyé ».',
      'Les réponses du client arrivent dans votre boîte email.',
    ],
  },
  {
    id: 'imprimer-devis',
    category: 'devis',
    title: 'Imprimer un devis ou l’enregistrer en PDF',
    summary: 'Sortez le devis sur papier ou en fichier PDF depuis la fenêtre d’impression.',
    keywords: ['imprimer', 'impression', 'pdf', 'papier', 'fichier', 'télécharger', 'exporter', 'enregistrer'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis', text: 'C’est le bouton « ⋯ » au bout de sa ligne.' },
      { title: 'Choisissez « Imprimer ou enregistrer en PDF »', text: 'Le devis s’ouvre dans un nouvel onglet, avec la fenêtre d’impression de votre navigateur.' },
      { title: 'Imprimez, ou enregistrez le fichier', text: 'Pour un PDF, choisissez l’enregistrement en PDF comme destination dans la fenêtre d’impression.' },
    ],
    notes: [
      'Le bouton « PDF » de la fiche du devis ouvre la même page.',
    ],
  },
  {
    id: 'statut-devis',
    category: 'devis',
    title: 'Changer le statut d’un devis',
    summary: 'Le statut dit où en est chaque devis, de la première demande au paiement.',
    keywords: ['statut', 'état', 'étape', 'avancement', 'validé', 'confirmé', 'acompte', 'payé', 'refus', 'refusé', 'brochure', 'dégustation', 'rendez-vous', 'événement'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur le devis dans la liste', text: 'Sa fiche s’ouvre à droite.' },
      { title: 'Choisissez le nouveau statut', text: 'Sous « Statut », cliquez sur l’étape atteinte. Le changement est pris en compte aussitôt.' },
      { title: 'Retrouvez le devis dans son volet', text: '« Validé », « Acompte reçu » et « Payé » le rangent dans « Confirmés ». « Refus client » et « Refus traiteur » le rangent dans « Refusés ».' },
      { title: 'Préparez l’événement', text: 'Un devis confirmé devient un événement : le bouton « Gérer l’événement », en bas de la fiche, ouvre sa préparation.' },
    ],
    notes: [
      'Avant la décision du client, un devis passe par « Nouveau », « Brochure envoyée », « Devis à faire », « Devis envoyé », « RDV/Dég à venir », « RDV/Dég fait » (rendez-vous ou dégustation) et « Devis final ».',
      'Quand un devis vient d’une demande reçue, son statut et celui de la demande changent ensemble.',
    ],
  },
  {
    id: 'pipeline-devis',
    category: 'devis',
    title: 'Suivre vos devis en colonnes',
    summary: 'La vue « Pipeline » range les devis par statut et laisse glisser un devis d’une colonne à l’autre.',
    keywords: ['pipeline', 'colonnes', 'tableau', 'kanban', 'glisser', 'déplacer', 'statut', 'suivi', 'prospection', 'avancement'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Pipeline »', text: 'Le bouton est en haut de la page Devis, à côté de « Liste ».' },
      { title: 'Parcourez les colonnes', text: 'Une colonne par statut, avec le nombre de devis et leur montant. Les étapes suivantes sont à droite.' },
      { title: 'Glissez un devis dans une autre colonne', text: 'Son statut change aussitôt.' },
    ],
    notes: [
      'Les demandes reçues y figurent aussi, avec l’étiquette « Prospect » et le bouton « Créer le devis ».',
      'La vue « Pipeline » est proposée sur tablette et sur ordinateur.',
    ],
  },
  {
    id: 'suivi-devis',
    category: 'devis',
    title: 'Noter vos relances sur un devis',
    summary: 'Chaque devis garde ses notes de suivi : appels, relances, échanges avec le client.',
    keywords: ['relance', 'relancer', 'notes', 'suivi', 'commercial', 'appel', 'rappel', 'rappeler', 'mémo', 'nom interne', 'renommer'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur le devis dans la liste', text: 'Sa fiche s’ouvre à droite.' },
      { title: 'Ouvrez l’onglet « Suivi commercial »' },
      { title: 'Écrivez votre note', text: 'Par exemple la date d’une relance et la réponse attendue.' },
      { title: 'Cliquez sur « Sauvegarder les notes »' },
    ],
    notes: [
      'Ces notes sont pour vous : elles ne figurent pas sur le devis du client.',
      'Dans l’onglet « Aperçu », « Nom du devis (interne) » donne au devis un nom à vous, par exemple « Mariage Camille et Hugo ».',
    ],
  },
  {
    id: 'dossiers-devis',
    category: 'devis',
    title: 'Ranger vos devis dans des dossiers',
    summary: 'Regroupez vos devis par saison, par type de réception ou par client.',
    keywords: ['dossier', 'dossiers', 'ranger', 'classer', 'organiser', 'trier', 'déplacer', 'sous-dossier', 'archive'],
    href: '/devis',
    steps: [
      { title: 'Créez un dossier', text: 'Cliquez sur « Nouveau dossier », donnez-lui un nom, une couleur et une icône, puis cliquez sur « Créer ».' },
      { title: 'Rangez un devis', text: 'Ouvrez son menu « ⋯ », choisissez « Déplacer vers un dossier », puis cliquez sur le dossier.' },
      { title: 'Ouvrez un dossier', text: 'Un clic sur sa tuile n’affiche que ses devis. « Mes devis » ramène à la liste complète.' },
      { title: 'Modifiez un dossier', text: 'Le bouton « ⋯ » de sa tuile change son nom, sa couleur et son icône, ou le supprime.' },
    ],
    notes: [
      'Vous pouvez aussi glisser un devis sur la tuile d’un dossier.',
      'Supprimer un dossier ne supprime pas ses devis : ils remontent d’un niveau.',
      'Dans un dossier ouvert, « Nouveau dossier » crée un sous-dossier et « Nouveau dans ce dossier » y crée un devis.',
    ],
  },
  {
    id: 'dupliquer-devis',
    category: 'devis',
    title: 'Dupliquer un devis',
    summary: 'Repartez d’un devis existant au lieu de tout ressaisir, et gardez-le comme modèle si vous le souhaitez.',
    keywords: ['dupliquer', 'copier', 'copie', 'double', 'refaire', 'réutiliser', 'modèle', 'base'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis, puis choisissez « Dupliquer »', text: 'Le menu est le bouton « ⋯ » au bout de la ligne.' },
      { title: 'Pour une copie, cliquez sur « Duplication simple »', text: 'La copie s’ouvre dans l’éditeur, avec le même client, les mêmes prestations et la même mise en page.' },
      { title: 'Pour garder aussi un modèle, donnez-lui un nom', text: 'Puis cliquez sur « Dupliquer + enregistrer modèle ».' },
    ],
    notes: [
      'La copie démarre au statut « Devis à faire » et reste dans le dossier de l’original.',
    ],
  },
  {
    id: 'modeles-devis',
    category: 'devis',
    title: 'Partir d’un modèle de devis',
    summary: 'Un modèle garde les prestations d’un devis type, prêtes à resservir.',
    keywords: ['modèle', 'modèles', 'gabarit', 'devis type', 'trame', 'base', 'réutiliser', 'bibliothèque', 'renommer'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Partir d’un modèle »', text: 'Le bouton est en haut de la page Devis.' },
      { title: 'Repérez le modèle qui convient', text: 'Chacun indique son nombre de prestations.' },
      { title: 'Cliquez sur « Utiliser »', text: 'Un nouveau devis s’ouvre dans l’éditeur avec les prestations du modèle.' },
    ],
    notes: [
      'Le bouton « Partir d’un modèle » apparaît une fois votre premier modèle enregistré, depuis « Dupliquer ».',
      'Le crayon renomme un modèle, la corbeille le supprime.',
    ],
  },
  {
    id: 'importer-devis',
    category: 'devis',
    title: 'Importer un devis fait ailleurs',
    summary: 'Un devis préparé dans un autre logiciel rejoint vos devis, avec son montant et son fichier.',
    keywords: ['importer', 'import', 'ancien devis', 'autre logiciel', 'word', 'pdf', 'fichier', 'document', 'joindre', 'reprendre'],
    href: '/devis',
    steps: [
      { title: 'Cliquez sur « Importer »', text: 'Le bouton est en haut de la page Devis.' },
      { title: 'Renseignez le client', text: '« Nouveau client » ou « Client existant ». Le prénom et le nom sont obligatoires.' },
      { title: 'Renseignez l’événement', text: 'La date est obligatoire. Ajoutez le type, le nombre de couverts et le montant total TTC.' },
      { title: 'Joignez le fichier du devis', text: 'PDF, Word, OpenDocument ou image.' },
      { title: 'Cliquez sur « Importer le devis »' },
    ],
    notes: [
      'Un devis importé arrive au statut « Validé », dans le volet « Confirmés » : il compte comme un événement à préparer.',
      'Il porte l’étiquette « Importé ». Dans son menu « ⋯ », « Modifier l’import » corrige ces informations ou remplace le fichier.',
      'Un devis importé ne s’envoie pas avec « Envoyer au client ».',
    ],
  },
  {
    id: 'marge-devis',
    category: 'devis',
    title: 'Suivre les coûts et la marge d’un devis',
    summary: 'Pour chaque devis : le chiffre d’affaires, les charges et la marge, prestation par prestation.',
    keywords: ['marge', 'coût', 'coûts', 'prix de revient', 'rentabilité', 'bénéfice', 'finance', 'charges', 'frais', 'chiffre d’affaires'],
    href: '/devis',
    steps: [
      { title: 'Ouvrez le menu du devis, puis choisissez « Marge et coûts »', text: 'Le menu est le bouton « ⋯ » au bout de la ligne.' },
      { title: 'Lisez les trois chiffres du haut', text: '« Chiffre d’affaires », « Charges » et « Marge brute », en euros et en pourcentage.' },
      { title: 'Saisissez un coût de revient', text: 'Cliquez dans la colonne « Coût » d’une prestation, tapez son coût unitaire hors taxes, puis validez avec la touche Entrée.' },
      { title: 'Ajoutez les frais propres à ce devis', text: 'Sous « Frais additionnels », cliquez sur « + Ajouter » : personnel en plus, transport, location.' },
      { title: 'Consultez la synthèse', text: 'En bas de la fiche, « Marge brute estimée » tient compte des coûts et des frais.' },
    ],
    notes: [
      'Le coût saisi est enregistré sur la prestation de votre catalogue : il sert à tous vos devis.',
      'Une ligne qui ne vient pas du catalogue n’a pas de coût, et sa marge n’est pas calculée.',
    ],
  },
];
