import type { HelpGuide } from '../types';

export const evenements: HelpGuide[] = [
  {
    id: 'evenements-liste',
    category: 'evenements',
    title: 'Retrouver vos événements',
    summary: 'Un devis confirmé devient un événement : la page « Événements » les réunit, à venir et passés.',
    keywords: ['événement', 'evenements', 'réception', 'prestation', 'devis validé', 'devis confirmé', 'acompte', 'à venir', 'passés', 'fiche événement', 'planning'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez « Événements » dans le menu', text: 'Chaque ligne donne la date, le client, le type de réception, le nombre de couverts, le statut et le lieu.' },
      { title: 'Passez de « À venir » à « Passés »', text: 'Les événements à venir vont du plus proche au plus lointain, les passés du plus récent au plus ancien.' },
      { title: 'Cliquez sur un événement pour ouvrir sa fiche', text: 'La fiche réunit quatre onglets de préparation : « Checklist », « Matériel », « Courses » et « Extras ».' },
      { title: 'Revenez au devis ou aux chiffres quand il le faut', text: '« Voir le devis » rouvre le devis d’origine. « Marge et coûts » affiche le chiffre d’affaires, les charges et la marge de l’événement.' },
    ],
    notes: [
      'Un devis apparaît ici dès que son statut est « Validé », « Acompte reçu » ou « Payé » et qu’il a une date.',
      'La barre de recherche du haut retrouve aussi un événement par le nom du client.',
    ],
  },
  {
    id: 'evenement-modifier',
    category: 'evenements',
    title: 'Modifier la date, le lieu ou les couverts d’un événement',
    summary: 'Corrigez les informations pratiques d’un événement depuis sa fiche, sans rouvrir le devis.',
    keywords: ['modifier', 'date', 'lieu', 'adresse', 'couverts', 'convives', 'invités', 'nombre de personnes', 'statut', 'reporter', 'décaler'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez la fiche de l’événement', text: 'Depuis « Événements », cliquez sur l’événement concerné.' },
      { title: 'Cliquez sur « Modifier »', text: 'La fenêtre « Modifier l’événement » affiche la date, les couverts, le lieu et le statut.' },
      { title: 'Changez ce qui a bougé', text: 'La date est obligatoire et le nombre de couverts doit être supérieur à zéro.' },
      { title: 'Cliquez sur « Enregistrer »', text: 'L’en-tête de la fiche reprend aussitôt les nouvelles informations.' },
    ],
    notes: [
      'Les lignes et le total du devis ne changent pas : pour revoir les quantités ou les prix, passez par « Voir le devis ».',
      'Après un changement de couverts, relancez « Calculer depuis le devis » dans l’onglet « Courses » pour mettre les quantités à jour.',
      'Avec un autre statut que « Validé », « Acompte reçu » ou « Payé », le devis quitte la liste des événements.',
    ],
  },
  {
    id: 'evenement-checklist',
    category: 'evenements',
    title: 'Préparer un événement avec la checklist',
    summary: 'Notez ce qu’il reste à faire avant le jour J et cochez les tâches au fur et à mesure.',
    keywords: ['checklist', 'tâches', 'à faire', 'liste', 'préparation', 'jour j', 'rétroplanning', 'cocher', 'organisation', 'pense-bête'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez la fiche de l’événement', text: 'L’onglet « Checklist » s’affiche en premier.' },
      { title: 'Ajoutez une tâche', text: 'Écrivez-la dans le champ « Ajouter une tâche », puis cliquez sur « Ajouter » ou appuyez sur Entrée.' },
      { title: 'Cochez ce qui est fait', text: 'La tâche est barrée et la barre d’avancement progresse.' },
      { title: 'Remettez les tâches dans l’ordre', text: 'Les deux flèches à droite de la ligne montent ou descendent la tâche. La corbeille la supprime.' },
    ],
    notes: [
      'Chaque événement a sa propre checklist.',
      'Chaque changement est enregistré aussitôt : il n’y a pas de bouton à valider.',
    ],
  },
  {
    id: 'evenement-materiel',
    category: 'evenements',
    title: 'Lister le matériel à emporter',
    summary: 'Dans l’onglet « Matériel », notez ce que vous emportez et cochez chaque article au chargement.',
    keywords: ['matériel', 'à emporter', 'chargement', 'camion', 'caisses', 'étuve', 'équipement', 'vaisselle', 'personnel', 'à préparer'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez l’onglet « Matériel » de l’événement', text: 'La partie « À préparer » liste ce que vous emportez.' },
      { title: 'Ajoutez un article', text: 'Saisissez son nom dans « Matériel à emporter », puis la quantité et l’unité, et cliquez sur « Ajouter ».' },
      { title: 'Cochez ce qui est prêt', text: 'La ligne cochée est barrée. La corbeille retire l’article de la liste.' },
      { title: 'Vérifiez les lignes marquées « du devis »', text: 'Le matériel et le personnel vendus dans le devis s’ajoutent d’eux-mêmes, avec leur quantité. Vous pouvez les cocher, pas les supprimer.' },
    ],
    notes: [
      'Une ligne du devis apparaît ici quand sa catégorie est « Matériel » ou « Personnel ».',
      'La vaisselle et le mobilier à louer se gèrent plus bas, dans la partie « Location » du même onglet.',
    ],
  },
  {
    id: 'evenement-location',
    category: 'evenements',
    title: 'Gérer la location de matériel d’un événement',
    summary: 'Listez la vaisselle et le mobilier à louer, fournisseur par fournisseur, et suivez ce qui est commandé.',
    keywords: ['location', 'louer', 'vaisselle', 'verres', 'assiettes', 'couverts', 'mobilier', 'nappes', 'loueur', 'fournisseur', 'commandé'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez l’onglet « Matériel », partie « Location »', text: 'Les articles sont regroupés par fournisseur, avec un sous-total par fournisseur et le « Total de la location ».' },
      { title: 'Générez la liste depuis vos modèles', text: '« Générer depuis mes modèles » calcule chaque article selon le nombre de couverts. Les articles générés avant sont remplacés, ceux ajoutés à la main sont conservés.' },
      { title: 'Ajoutez un article à la main', text: '« Ajouter un article » demande le nom, la quantité, l’unité, le prix unitaire HT, le fournisseur et une note.' },
      { title: 'Cochez les articles commandés', text: 'La mention « Commandé » s’affiche sous l’article.' },
      { title: 'Imprimez la liste', text: '« Imprimer » ouvre la liste par fournisseur dans un nouvel onglet, avec les prix et le total.' },
    ],
    notes: [
      'Le bouton « Générer depuis mes modèles » apparaît dès que vous avez au moins un modèle de location.',
      'Le crayon rouvre un article. La case « Commandé à part » le retire alors de la page « Location », qui regroupe les besoins de la saison.',
    ],
  },
  {
    id: 'evenement-courses',
    category: 'evenements',
    title: 'Préparer la liste de courses d’un événement',
    summary: 'La liste se calcule à partir du devis : la quantité par convive de chaque ingrédient, multipliée par le nombre de couverts.',
    keywords: ['courses', 'liste de courses', 'achats', 'ingrédients', 'quantités', 'marché', 'calcul', 'couverts', 'convives', 'commande', 'fournisseur'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez l’onglet « Courses » de l’événement' },
      { title: 'Cliquez sur « Calculer depuis le devis »', text: 'Pour chaque prestation du devis, l’app multiplie la quantité par convive de ses ingrédients par le nombre de couverts de l’événement. Un message indique combien d’ingrédients ont été calculés.' },
      { title: 'Ajoutez ce qui manque avec « Ajouter un ingrédient »', text: 'Cherchez l’ingrédient, puis indiquez la quantité, le fournisseur et une note. La ligne porte la mention « Ajout manuel ».' },
      { title: 'Cochez les articles pris', text: 'Les lignes sont regroupées par fournisseur et la barre suit l’avancement.' },
      { title: 'Créez les commandes ou imprimez', text: '« Créer les commandes » prépare une commande en brouillon par fournisseur, à retrouver dans « Commandes ». « Imprimer » sort la liste par fournisseur.' },
    ],
    notes: [
      'Au recalcul, les lignes ajoutées à la main sont conservées et une ligne déjà cochée reste cochée.',
      'Une prestation sans ingrédient ne donne aucune ligne : le message du calcul la signale. Reliez d’abord les ingrédients à vos prestations.',
      'Un ingrédient sans fournisseur ne figure dans aucune commande.',
    ],
  },
  {
    id: 'evenement-mode-courses',
    category: 'evenements',
    title: 'Faire les courses avec le mode courses',
    summary: 'La liste de l’événement en grandes lignes à cocher, pour le magasin ou le marché.',
    keywords: ['mode courses', 'courses', 'magasin', 'marché', 'grossiste', 'téléphone', 'mobile', 'cocher', 'rayon', 'panier'],
    href: '/evenements',
    steps: [
      { title: 'Dans l’onglet « Courses », cliquez sur « Mode courses »', text: 'Le bouton apparaît dès que la liste contient au moins une ligne.' },
      { title: 'Touchez un article pour le cocher', text: 'Il est barré et le compteur du haut avance. Touchez-le à nouveau pour le décocher.' },
      { title: 'Filtrez par catégorie', text: 'Les boutons sous le compteur n’affichent qu’une famille d’ingrédients. « Tout » les remet toutes.' },
      { title: 'Revenez à la fiche', text: '« Retour à l’événement » ramène à la fiche. Les articles cochés ici le sont aussi dans l’onglet « Courses ».' },
    ],
    notes: [
      'Le titre et le compteur restent visibles pendant que la liste défile.',
    ],
  },
  {
    id: 'evenement-extras',
    category: 'evenements',
    title: 'Affecter des extras à un événement',
    summary: 'Choisissez qui travaille sur l’événement, précisez l’heure d’arrivée et les consignes, puis suivez qui a confirmé.',
    keywords: ['extras', 'personnel', 'serveurs', 'cuisiniers', 'barman', 'équipe', 'staff', 'mission', 'fiche mission', 'lien', 'confirmer', 'affecter'],
    href: '/evenements',
    steps: [
      { title: 'Ouvrez l’onglet « Extras » de l’événement' },
      { title: 'Cliquez sur « Affecter un extra »', text: 'Choisissez la personne, son heure d’arrivée et ses consignes. Cochez « Chargé des courses » si elle s’en occupe.' },
      { title: 'Suivez les réponses', text: 'Sur chaque personne, passez de « À solliciter » à « Confirmé », puis à « Présent » le jour J. Le compteur du haut indique combien ont confirmé.' },
      { title: 'Transmettez à chacun le lien de sa fiche mission', text: 'L’icône de lien copie l’adresse de sa page personnelle et « Copié » s’affiche. Collez-la dans un SMS ou un email : la personne y voit la date, l’heure d’arrivée, le lieu et ses consignes, sans créer de compte.' },
      { title: 'Imprimez les fiches', text: '« Fiches mission » ouvre une page à imprimer avec la fiche de chaque extra affecté.' },
    ],
    notes: [
      'Le bouton « Affecter un extra » reste grisé quand tous vos extras sont déjà sur l’événement. Ajoutez vos extras dans la page « Extras ».',
      'L’app n’envoie pas le lien elle-même : c’est vous qui le transmettez.',
      'Le lien est le même pour toutes les missions d’une personne : sa page liste ses missions à venir.',
    ],
  },
  {
    id: 'calendrier',
    category: 'evenements',
    title: 'Lire le calendrier',
    summary: 'Le mois en un coup d’œil : événements confirmés et devis en cours, jour par jour.',
    keywords: ['calendrier', 'agenda', 'planning', 'mois', 'dates', 'disponibilité', 'confirmés', 'en cours', 'jour', 'semaine'],
    href: '/calendrier',
    steps: [
      { title: 'Changez de mois avec les flèches', text: '« Aujourd’hui » revient au mois en cours. Sous le titre, un résumé compte les événements confirmés, les devis en cours et les couverts du mois.' },
      { title: 'Repérez les deux couleurs', text: 'Un nom sur fond plein est un événement confirmé. Un nom encadré est un devis encore en cours.' },
      { title: 'Cliquez sur un jour', text: 'Le panneau de droite liste les événements de ce jour et leur total de couverts. « Voir tout le mois » revient à la liste du mois.' },
      { title: 'Affichez seulement les confirmés', text: 'Le bouton « Confirmés » masque les devis en cours. « Tous » les remet.' },
      { title: 'Ouvrez un événement depuis la liste', text: 'Un événement confirmé ouvre sa fiche, un devis en cours ouvre le devis.' },
    ],
    notes: [
      'Les devis refusés n’apparaissent pas dans le calendrier.',
      'Un devis sans date n’apparaît pas non plus.',
    ],
  },
  {
    id: 'courses-globales',
    category: 'evenements',
    title: 'Regrouper les courses de plusieurs événements',
    summary: 'Additionnez les listes de courses de tous vos événements sur une période, fournisseur par fournisseur.',
    keywords: ['courses globales', 'achats groupés', 'regrouper', 'période', 'semaine', 'besoins', 'ingrédients', 'fournisseur', 'total', 'commande groupée'],
    href: '/courses-globales',
    steps: [
      { title: 'Ouvrez « Courses globales » dans le menu « Catalogue »' },
      { title: 'Choisissez la « Date de début » et la « Date de fin »' },
      { title: 'Cliquez sur « Calculer les besoins »', text: 'Les quantités de chaque ingrédient sont additionnées et rangées par fournisseur. À droite de chaque ligne figurent les dates des événements concernés.' },
      { title: 'Imprimez la liste', text: '« Imprimer » sort la liste complète, fournisseur par fournisseur.' },
    ],
    notes: [
      'Seuls les événements confirmés dont la liste de courses est remplie sont comptés.',
      'Cette page ne fait que lire les listes : pour changer une quantité, ouvrez l’onglet « Courses » de l’événement.',
    ],
  },
  {
    id: 'location-globale',
    category: 'evenements',
    title: 'Regrouper la location de plusieurs événements',
    summary: 'Additionnez le matériel à louer sur une période et sortez un bon par fournisseur.',
    keywords: ['location', 'location globale', 'vaisselle', 'loueur', 'saison', 'période', 'bon de commande', 'regrouper', 'matériel', 'verres'],
    href: '/location-globale',
    steps: [
      { title: 'Ouvrez « Location » dans le menu « Catalogue »', text: 'La page s’intitule « Location globale ».' },
      { title: 'Choisissez les dates, puis cliquez sur « Calculer les besoins »', text: 'Les événements de la période sont rappelés en tête, avec leur date et leur nombre de convives.' },
      { title: 'Lisez les totaux par fournisseur', text: 'Pour chaque article : la quantité totale, le coût, et le détail par date d’événement.' },
      { title: 'Sortez les bons', text: '« Bon fournisseur » prépare le bon de commande d’un seul loueur. « Bon général PDF » réunit tous les fournisseurs.' },
    ],
    notes: [
      'Seuls les événements confirmés sont comptés.',
      'Un article marqué « Commandé à part » dans la fiche d’un événement n’est pas repris ici.',
    ],
  },
];
