import type { HelpGuide } from '../types';

export const stock: HelpGuide[] = [
  {
    id: 'ingredients',
    category: 'stock',
    title: 'Créer et gérer vos ingrédients',
    summary: 'Votre liste d’ingrédients sert aux prestations, aux listes de courses, au stock et aux commandes.',
    keywords: ['ingrédients', 'produits', 'matières premières', 'denrées', 'unité', 'catégorie', 'prix d’achat', 'seuil', 'fournisseur', 'csv', 'importer'],
    href: '/ingredients',
    steps: [
      { title: 'Ouvrez « Ingrédients » dans le menu « Catalogue »', text: 'Les boutons de catégorie et le champ « Rechercher… » filtrent la liste.' },
      { title: 'Cliquez sur « Ajouter »', text: 'Donnez un nom, une catégorie et une unité : kg, L, Bouteille, Botte…' },
      { title: 'Choisissez le fournisseur préféré', text: 'Il est repris dans les listes de courses calculées, et c’est chez lui que les commandes sont préparées.' },
      { title: 'Renseignez le seuil d’alerte et le prix unitaire', text: 'Le seuil déclenche l’alerte de stock bas. Le prix sert à chiffrer le stock et les commandes.' },
      { title: 'Validez avec « Ajouter »', text: 'Pour modifier ou supprimer un ingrédient, survolez sa carte : un crayon et une corbeille apparaissent.' },
    ],
    notes: [
      'Pendant que vous tapez le nom, une liste « Open Food Facts » peut proposer des produits : en choisir un reprend son nom et sa photo. Vous pouvez l’ignorer et continuer à taper.',
      'Le bouton « CSV » importe une liste depuis un fichier à trois colonnes (catégorie, nom, unité). Les ingrédients déjà présents sont signalés et laissés de côté.',
      'Vos fournisseurs se gèrent aussi en bas de cette page, dans le bloc « Fournisseurs ».',
    ],
  },
  {
    id: 'stock',
    category: 'stock',
    title: 'Suivre votre stock et les alertes de stock bas',
    summary: 'Enregistrez les entrées et les sorties de chaque ingrédient et repérez ce qui passe sous le seuil.',
    keywords: ['stock', 'inventaire', 'réserve', 'entrée', 'sortie', 'alerte', 'stock bas', 'rupture', 'épuisé', 'seuil', 'historique', 'mouvements'],
    href: '/stock',
    steps: [
      { title: 'Ouvrez « Stock » dans le menu', text: 'En tête : le nombre d’ingrédients, ceux en « Stock bas » et ceux marqués « Épuisé ». Un clic sur l’un de ces deux cadres n’affiche que les ingrédients concernés ; « Tous » revient à la liste complète.' },
      { title: 'Consultez l’historique d’un ingrédient', text: 'L’icône d’horloge liste ses mouvements, du plus récent au plus ancien, avec la raison et la date.' },
      { title: 'Cliquez sur « Entrée » à la réception d’une marchandise', text: 'Saisissez la quantité et, si vous voulez, la raison. La fenêtre affiche le stock avant et après.' },
      { title: 'Cliquez sur « Sortie » pour ce qui quitte la réserve', text: 'Le geste est le même. Une sortie ne peut pas dépasser le stock disponible.' },
      { title: 'Cliquez sur « Valider »', text: 'Le mouvement est enregistré et le stock de l’ingrédient est recalculé.' },
    ],
    notes: [
      'Un ingrédient passe en « Stock bas » quand son stock est inférieur ou égal à son seuil d’alerte. Le seuil se règle dans la fiche de l’ingrédient, page « Ingrédients ».',
      'Le chiffre à côté de « Stock » dans le menu compte les ingrédients en stock bas.',
      'Marquer une commande fournisseur comme reçue ajoute ses quantités au stock.',
    ],
  },
  {
    id: 'commande-fournisseur',
    category: 'stock',
    title: 'Passer une commande fournisseur',
    summary: 'Préparez un bon de commande : un fournisseur, des ingrédients, des quantités.',
    keywords: ['commande', 'bon de commande', 'achat', 'fournisseur', 'approvisionnement', 'réassort', 'brouillon', 'commander'],
    href: '/commandes',
    steps: [
      { title: 'Ouvrez « Commandes », puis cliquez sur « Nouvelle commande »' },
      { title: 'Choisissez le fournisseur' },
      { title: 'Ajoutez les ingrédients', text: 'Tapez quelques lettres dans « Rechercher un ingrédient… » et cliquez sur celui qui convient. Son prix unitaire est repris de sa fiche.' },
      { title: 'Ajustez les quantités et les prix', text: 'Le « Total HT » se recalcule à chaque changement. Une note peut préciser la livraison.' },
      { title: 'Cliquez sur « Créer la commande »', text: 'La commande est enregistrée avec le statut « Brouillon », en tête de liste.' },
    ],
    notes: [
      'Le bouton « Créer la commande » reste grisé tant qu’il manque le fournisseur ou un article.',
      'Depuis l’onglet « Courses » d’un événement, « Créer les commandes » prépare d’un coup un brouillon par fournisseur.',
    ],
  },
  {
    id: 'commande-suivi',
    category: 'stock',
    title: 'Suivre une commande jusqu’à la réception',
    summary: 'Brouillon, envoyée, reçue : faites avancer chaque commande et mettez le stock à jour à la livraison.',
    keywords: ['commande', 'suivi', 'livraison', 'réception', 'envoyée', 'reçue', 'brouillon', 'bon de commande', 'imprimer', 'stock'],
    href: '/commandes',
    steps: [
      { title: 'Filtrez avec les cadres du haut', text: '« Brouillons » et « Envoyées » n’affichent que les commandes de ce statut, avec leur montant total. « Total » les affiche toutes.' },
      { title: 'Vérifiez le contenu avec « Détails »', text: 'La fenêtre liste les articles, les quantités, les prix et le total HT.' },
      { title: 'Imprimez le bon de commande', text: 'L’icône d’imprimante ouvre le bon dans un nouvel onglet, pour l’imprimer ou l’enregistrer en PDF.' },
      { title: 'Cliquez sur « Marquer envoyée »', text: 'À faire une fois la commande passée auprès du fournisseur. La date d’envoi s’affiche sous son nom.' },
      { title: 'À la livraison, cliquez sur « Marquer reçue (+stock) »', text: 'Après confirmation, les quantités de la commande entrent dans le stock.' },
    ],
    notes: [
      'L’app n’envoie pas la commande au fournisseur : transmettez-lui le bon vous-même.',
      'La corbeille supprime une commande, après confirmation. Cette suppression est définitive.',
    ],
  },
  {
    id: 'fournisseurs',
    category: 'stock',
    title: 'Gérer vos fournisseurs',
    summary: 'Un carnet d’adresses pour vos grossistes et vos loueurs, utilisé par les ingrédients, les courses, la location et les commandes.',
    keywords: ['fournisseur', 'fournisseurs', 'grossiste', 'loueur', 'primeur', 'boucher', 'contact', 'coordonnées', 'carnet d’adresses', 'téléphone'],
    href: '/fournisseurs',
    steps: [
      { title: 'Ouvrez « Fournisseurs » dans le menu « Catalogue »' },
      { title: 'Cliquez sur « Ajouter »', text: 'Le formulaire « Nouveau fournisseur » s’ouvre sous la liste.' },
      { title: 'Renseignez le nom et les coordonnées', text: 'Seul le nom est obligatoire. Le téléphone, l’email, l’adresse et les notes (jours de livraison, minimum de commande) sont facultatifs.' },
      { title: 'Cliquez sur « Enregistrer »', text: 'Le fournisseur rejoint la liste, classée par ordre alphabétique.' },
      { title: 'Modifiez ou supprimez', text: 'Le crayon rouvre la fiche. La corbeille supprime le fournisseur, après confirmation.' },
    ],
    notes: [
      'Un champ de recherche apparaît au-dessus de la liste à partir de six fournisseurs.',
      'Supprimer un fournisseur le retire des articles de location qui lui étaient rattachés.',
    ],
  },
];
